name: Lint

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
  workflow_call:

jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/requirements*.txt"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install black
      - run: echo "::add-matcher::./.github/problem_matchers/black.jsonc"
      - run: black --check ./syne_tune/backend
      - run: echo "::remove-matcher owner=black::"

  flake8:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/requirements*.txt"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install flake8
      - run: echo "::add-matcher::./.github/problem_matchers/flake8.jsonc"
      - run: flake8 ./syne_tune/backend
      - run: echo "::remove-matcher owner=flake8::"
