name: Typecheck

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
  workflow_call:

jobs:
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/requirements*.txt"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install '.[extra]'
      - run: echo "::add-matcher::./.github/problem_matchers/mypy.jsonc"
      - run: mypy ./benchmarking ./examples ./syne_tune ./tst
      - run: echo "::remove-matcher owner=mypy::"

  pyright:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/requirements*.txt"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install '.[extra]'
      - run: echo "::add-matcher::./.github/problem_matchers/pyright.jsonc"
      - run: pyright ./benchmarking ./examples ./syne_tune ./tst
      - run: echo "::remove-matcher owner=pyright::"
      - run: pyright --verifytypes syne_tune --ignoreexternal --pythonversion 3.10 --pythonplatform Linux --verbose
